/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ABSTRACTGATEWAYSERVER_H_
#define JSONRPC_CPP_STUB_ABSTRACTGATEWAYSERVER_H_

#include <jsonrpccpp/server.h>

class AbstractGatewayServer : public jsonrpc::AbstractServer<AbstractGatewayServer>
{
    public:
        AbstractGatewayServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<AbstractGatewayServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("getinfo", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractGatewayServer::getinfoI);
        }

        inline virtual void getinfoI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getinfo();
        }
        virtual Json::Value getinfo() = 0;
};

#endif //JSONRPC_CPP_STUB_ABSTRACTGATEWAYSERVER_H_
