/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_GATEWAYSERVER_H_
#define JSONRPC_CPP_STUB_GATEWAYSERVER_H_

#include <jsonrpccpp/server.h>

class GatewayServer : public jsonrpc::AbstractServer<GatewayServer>
{
    public:
        GatewayServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<GatewayServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("getinfo", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &GatewayServer::getinfoI);
        }

        inline virtual void getinfoI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getinfo();
        }
        virtual Json::Value getinfo() = 0;
};

#endif //JSONRPC_CPP_STUB_GATEWAYSERVER_H_
