/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_PLATFORMCLIENT_H_
#define JSONRPC_CPP_STUB_PLATFORMCLIENT_H_

#include <jsonrpccpp/client.h>

class PlatformClient : public jsonrpc::Client
{
    public:
        PlatformClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        Json::Value getblockchaininfo() 
        {
            Json::Value p;
            p = Json::nullValue;
            Json::Value result = this->CallMethod("getblockchaininfo",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
};

#endif //JSONRPC_CPP_STUB_PLATFORMCLIENT_H_
